sudo: required
dist: bionic
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libopencv-dev
            - libgsl0-dev
            - libopenscenegraph-dev
            - freeglut3-dev
            - libboost-system-dev
            - libboost-thread-dev
            - qt4-dev-tools
            - pyside-tools
            - libxt-dev
            - pyqt4-dev-tools
            - libboost-all-dev
            - libccd
            - libccd-dev
            - libflann-dev
            - zeroc-ice-all-runtime
            - zeroc-ice-all-dev

      env: COMPILER=g++-5

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv B6391CB2CFBA643D
  - sudo apt-add-repository "deb [arch=amd64] http://zeroc.com/download/Ice/3.7/ubuntu18.04 stable main"
  - sudo apt-get update -qq
  - sudo apt-get install -y libzeroc-ice3.7
  - wget 'https://zeroc.com/download/ice/3.7/ubuntu18.04/pool/main/z/zeroc-ice/zeroc-ice-slice_3.7.2-1_all.deb'
  - sudo dpkg -i zeroc-ice-slice_3.7.2-1_all.deb
  - wget 'https://zeroc.com/download/ice/3.7/ubuntu18.04/pool/main/z/zeroc-ice/zeroc-ice-compilers_3.7.2-1_amd64.deb'
  - sudo dpkg -i zeroc-ice-compilers_3.7.2-1_amd64.deb  
  - wget 'https://zeroc.com/download/ice/3.7/ubuntu18.04/pool/main/z/zeroc-ice/libzeroc-ice-dev_3.7.2-1_amd64.deb'
  - sudo dpkg -i libzeroc-ice-dev_3.7.2-1_amd64.deb
  - sudo apt-get install zeroc-ice-all-runtime zeroc-ice-all-dev
# Commands to try and fix check failures
#  - sudo rm /var/lib/apt/lists/lock
#  - sudo rm /var/cache/apt/archives/lock
#  - sudo rm /var/lib/dpkg/lock

script:
  - export ROBOCOMP="/home/travis/build/robocomp/robocomp"
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DFCL_SUPPORT=1 . && make
