sudo: required
dist: bionic
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libopencv-dev
            - libgsl0-dev
            - libopenscenegraph-dev
            - freeglut3-dev
            - libboost-system-dev
            - libboost-thread-dev
            - qt4-dev-tools
            - pyside-tools
            - libxt-dev
            - pyqt4-dev-tools
            - libboost-all-dev
            - libccd
            - libccd-dev
            - libflann-dev
            - zeroc-ice-all-runtime
            - zeroc-ice-all-dev
            - pyside-tools

      env: COMPILER=g++-5

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5E6DA83306132997
  - sudo apt-add-repository "deb http://zeroc.com/download/Ice/3.6/ubuntu16.04 stable main"
  - sudo apt-get update -qq
  - sudo apt-get install zeroc-ice-all-runtime zeroc-ice-all-dev
# Commands to try and fix check failures
#  - sudo rm /var/lib/apt/lists/lock
#  - sudo rm /var/cache/apt/archives/lock
#  - sudo rm /var/lib/dpkg/lock

script:
  - export ROBOCOMP="/home/travis/build/robocomp/robocomp"
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DFCL_SUPPORT=1 . && make
