--- 
dist: bionic
language: cpp
matrix: 
  include: 
    - 
      addons: 
        apt: 
          packages: 
            - ice36-slice
            - python3-zeroc-ice
            - cmake-qt-gui
            - freeglut3-dev
            - g++
            - git
            - git-annex
            - libboost-all-dev
            - libboost-filesystem-dev
            - libboost-system-dev
            - libboost-test-dev
            - libboost-thread-dev
            - libccd
            - libccd-dev
            - libflann-dev
            - libgsl-dev
            - libgsl0-dev
            - libopencv-dev
            - libopenscenegraph-dev
            - libxt-dev
            - libzeroc-ice-dev
            - pyqt4-dev-tools
            - pyside-tools
            - python-libxml2
            - "python-numpy python-pyside"
            - python-pip
            - python-pyparsing
            - python-xmltodict
            - python-zeroc-ice
            - qt4-dev-tools
            - slice2cpp
            - zeroc-ice
            - zeroc-ice-utils
            - zeroc-ice36-dev
          sources: 
            - ubuntu-toolchain-r-test
      compiler: gcc
      env: COMPILER=g++
before_install: 
  - "sudo apt-get update -qq"
  - "sudo apt-get -y install zeroc-ice36-dev python-zeroc-ice python3-zeroc-ice ice36-slice"
script: 
  - "export ROBOCOMP=\"/home/travis/build/robocomp/robocomp\""
  - "cmake -DCMAKE_CXX_COMPILER=$COMPILER -DFCL_SUPPORT=1 . && make"
sudo: required
