sudo: required
dist: bionic
language: cpp

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-11

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 5E6DA83306132997
  - sudo apt-add-repository "deb http://zeroc.com/download/Ice/3.6/ubuntu16.04 stable main"
  - sudo apt-get update -qq
  - sudo apt-get install -y git git-annex cmake g++ libgsl-dev libopenscenegraph-dev cmake-qt-gui zeroc-ice-all-dev freeglut3-dev libboost-system-dev libboost-thread-dev qt4-dev-tools python-pip  python-pyparsing python-numpy python-pyside pyside-tools libxt-dev libboost-test-dev libboost-filesystem-dev python-libxml2 python-xmltodict libccd-dev python-zeroc-ice zeroc-ice-all-runtime
  - sudo apt-get install -y libfcl-dev
# Commands to try and fix check failures
#  - sudo rm /var/lib/apt/lists/lock
#  - sudo rm /var/cache/apt/archives/lock
#  - sudo rm /var/lib/dpkg/lock

script:
  - export ROBOCOMP="/home/travis/build/robocomp/robocomp"
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DFCL_SUPPORT=1 . && make
